### PR TITLE
fix: storefinder search improvements

### LINKED ISSUE #1372: Storefinder: Search improvements
- [x] 1. Searching anything in store finder always returns the same list with 23 stores. 
_Update: After talk with @Xymmer and @frankgrupe turned out that on our dev OCC servers some pieces of functionality for geo location are disabled. We are not able to get valid results. So for now we should keep that list as it is and use exactly what OCC returns wtih the query. In a future we can test it hard with real values in SCC env._

- [x] 2. Add information on the page about results based on pagination (example: 1-10 from 49 stores found).
- [x] 3. Selected item on a list should have different background.

Example:
requirements

### PR DESCRIPTION
**Pull request by Matejk00**
Closes #1372

### CODE REVIEW

File: projects/storefrontlib/src/lib/store-finder/components/store-finder-search-result/store-finder-list/store-finder-list.component.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ export class StoreFinderListComponent {
   @ViewChild('storeMap')
   storeMap: StoreFinderMapComponent;
 
-  selectedStore: number;
+  selectedStore = 0;
```
Comment (mszczepaniak) [inline projects/storefrontlib/src/lib/store-finder/components/store-finder-search-result/store-finder-list/store-finder-list.component.ts]: Should we initialize selectedStore in the ngOnInit instead of here?

Comment (Matejk00) [reply projects/storefrontlib/src/lib/store-finder/components/store-finder-search-result/store-finder-list/store-finder-list.component.ts]: I think that is not a mistake, we assign 0 as default, we don't need to do this in component's lifecycle hooks.
