### PR TITLE
fix(storefront): stack multiple product thumbnails in carousel

### LINKED ISSUE #3151: Samsung S10+: Pdp with many thumbnails does not fit on the screen
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Samsung galaxy S10+ 
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Go to the pdp of product 1934795

**Actual Result**
Looks disproportionate. 
The first thumbnail is cut and it spreads over the storefront on top (white portion). 
bd5e6a97-e99f-4f94-b300-52905284dfd7

### PR DESCRIPTION
**Pull request by tobi-or-not-tobi**
This fix requires to store the product thumbnails in a carousel, we (UI design) intended to do this anyway.

fixes #3151

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/product/product-images/product-images.component.ts [hunk 1]
```diff
@@ -1,68 +1,76 @@
 import { ChangeDetectionStrategy, Component } from '@angular/core';
 import { Product } from '@spartacus/core';
-import { BehaviorSubject, combineLatest, Observable } from 'rxjs';
-import { filter, map } from 'rxjs/operators';
+import { CarouselItem } from 'projects/storefrontlib/src/shared';
```
Comment (LTiger14) [inline projects/storefrontlib/src/cms-components/product/product-images/product-images.component.ts]: Wrong import

File: projects/storefrontlib/src/cms-components/product/product-images/product-images.module.ts [hunk 2]
```diff
@@ -2,6 +2,7 @@ import { CommonModule } from '@angular/common';
 import { NgModule } from '@angular/core';
 import { RouterModule } from '@angular/router';
 import { CmsConfig, ConfigModule } from '@spartacus/core';
+import { CarouselModule } from 'projects/storefrontlib/src/shared';
```
Comment (LTiger14) [inline projects/storefrontlib/src/cms-components/product/product-images/product-images.module.ts]: Also wrong import

File: projects/storefrontstyles/scss/components/product/carousel/_carousel.scss [hunk 3]
```diff
@@ -56,8 +56,9 @@
           justify-content: space-between;
           padding-bottom: 10px;
           color: var(--cx-g-color-text);
+
           cx-media {
-            height: 20vmin;
+            // height: 20vmin;
```
Comment (LTiger14) [inline projects/storefrontstyles/scss/components/product/carousel/_carousel.scss]: This can probably go 😉

File: projects/storefrontstyles/scss/components/product/details/_product-images.scss [hunk 4]
```diff
@@ -52,56 +52,30 @@ $productThumbSize: 75px !default;
...
-
     cx-media {
-      width: $productThumbSize;
-      height: $productThumbSize;
-
-      &.is-missing {
-        min-height: $productThumbSize;
-        background-size: $productThumbSize;
-      }
+      // width: $productThumbSize;
```
Comment (LTiger14) [inline projects/storefrontstyles/scss/components/product/details/_product-images.scss]: The comments can be cleaned up 🧽

File: projects/storefrontlib/src/cms-components/product/product-images/product-images.component.ts [hunk 5]
```diff
@@ -1,68 +1,76 @@
...
-  loadHandler(): void {
-    this.clearWaitList();
-  }
-
-  private startWaiting(el: HTMLElement): void {
-    this.clearWaitList();
-    el.classList.add(WAITING_CLASS);
-    this.waiting = el;
-  }
+  mainMediaIsLoaded(): void {}
```
Comment (LTiger14) [inline projects/storefrontlib/src/cms-components/product/product-images/product-images.component.ts]: Is it possible to live without this?

File: projects/storefrontlib/src/cms-components/product/product-images/product-images.component.ts [hunk 6]
```diff
@@ -1,68 +1,76 @@
...
-        : product.images && product.images.PRIMARY
-        ? product.images.PRIMARY
-        : {}
+  private product$: Observable<
+    Product
+  > = this.currentProductService.getProduct().pipe(
+    filter(Boolean),
+    distinctUntilChanged(),
+    tap((p: Product) =>
+      this.mainMediaContainer.next(p.images ? p.images.PRIMARY : null)
```
Comment (LTiger14) [inline projects/storefrontlib/src/cms-components/product/product-images/product-images.component.ts]: I think there is a bug here. It might be because of the null but I feel like the media component should handle it 🤷‍♂ . Anyway, for a product with no image we get nothing instead of the "no image" image.

Screen Shot 2019-06-13 at 10 47 18 AM

File: projects/storefrontlib/src/cms-components/product/product-images/product-images.component.ts [hunk 7]
```diff
@@ -1,68 +1,76 @@
...
+  mainMediaContainer = new BehaviorSubject(null);
 
-  imageContainer$ = combineLatest(this.product$, this._imageContainer$).pipe(
-    map(([product, container]) =>
-      container
-        ? container
-        : product.images && product.images.PRIMARY
-        ? product.images.PRIMARY
-        : {}
+  private product$: Observable<
```
Comment (LTiger14) [inline projects/storefrontlib/src/cms-components/product/product-images/product-images.component.ts]: Also just thought about this, since the `product$` variable is only used for the `thumbs$` lower could it just be `thumbs$` here and you add the map at the end of this pipe?

Comment (tobi-or-not-tobi) [reply projects/storefrontlib/src/cms-components/product/product-images/product-images.component.ts]: I prefer to keep it, so it's more clear that the tap on the product is creating the initial container.

**Comment by LTiger14** [comment]
LGTM
