### PR TITLE
fix: improve focus in tabs on productPage

### LINKED ISSUE #4930: Fix productPage tabs' focus

### PR DESCRIPTION
**Pull request by kacperknapik**
Closes #4930

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.ts [hunk 1]
```diff
@@ -37,11 +46,19 @@ export class ProductReviewsComponent {
 
   initiateWriteReview(): void {
     this.isWritingReview = true;
+
+    setTimeout(() => {
```
Comment (Zeyber) [inline projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.ts]: Can we do this another way without `setTimeout`? Its use is a big nono for SSR.
https://sap.github.io/cloud-commerce-spartacus-storefront-docs/server-side-rendering-coding-guidelines/#working-with-timeouts
