### PR TITLE
Fixing e2e search tests (#2682)

### LINKED ISSUE #2682: Failing regression tests: Mobile tests
All mobile tests (except for login) failed on the pipeline last night. 
- [ ] All mobile tests

Search box was refactored last week, so possibly this is part of the reason for failing tests.
- [x] mobile/product-search-mobile.e2e-spec: 1 failing
Search results "before all" hook for "should be able to search and get results":
CypressError: Timed out retrying: Expected to find element: 'cx-searchbox [aria-label="Search"]', but never found it.
- [x] mobile/product-search-product-type-flow-mobile.e2e-spec: 1 failing
Product search should be able to search with specific product type:
CypressError: Timed out retrying: Expected to find element: 'cx-searchbox [aria-label="Search"]', but never found it.
- [x] mobile/product-search-rating-flow-mobile.e2e-spec: 1 failing
Product search should be able to search and show product rating:
CypressError: Timed out retrying: Expected to find element: 'cx-searchbox [aria-label="Search"]', but never found it.
- [x] mobile/product-search-store-flow-mobile.e2e-spec: 1 failing
Product search should be able to search with store filtering:
CypressError: Timed out retrying: Expected to find element: 'cx-searchbox [aria-label="Search"]', but never found it.

The following failing mobile search test has a ticket: GH-2642
mobile/product-search-pricing-flow-mobile.e2e-spec: 1 failing
Product search should be able to search with price:
CypressError: Timed out retrying: expected '<a.cx-product-name>' to contain 'DSC-S930'

### PR DESCRIPTION
**Pull request by hackergil**
Fixes #2682

### CODE REVIEW

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts [hunk 1]
```diff
@@ -1,21 +1,17 @@
...
-    `${apiUrl}/rest/v2/electronics-spa/products/search?fields=*&sort=price-asc*`
-  ).as('query_price_asc');
+  createGenericQuery('query');
+  createQuery('price-asc', 'query_price_asc');
 
   // Click on a Category
   cy.get('header').within(() => {
-    cy.get('.nav-link')
+    cy.get('cx-navigation-ui')
       .contains('Digital Cameras')
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: Ran 5 headless (dev-17) tests and this fails 3 times

CypressError: Timed out retrying: cy.click() failed because this element is not visible:

`a tag role="link" ng-reflect-router-link="/Open-Catalogue/Cameras/Digita" href="/electronics-spa/en/USD/Open-Catalogue/Cameras/Digital-Cameras/Digital-Compacts/c/576">Compact...

This element a tag is not visible because it has an effective width and height of: '0 x 0' pixels.`

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-rating-flow.ts [hunk 2]
```diff
@@ -1,20 +1,24 @@
...
-export const tabsHeaderList = 'cx-product-tabs .details > h3';
+export const tabsHeaderList = 'cx-tab-paragraph-container > h3';
+
+const productSelector = 'cx-product-list-item';
 
 export function productRatingFlow(mobile?: string) {
-  // Search for a product
-  cy.get('cx-searchbox input').type('DSC-N1{enter}');
+  clickSearchIcon();
+  const productName = 'DSC-N1';
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-rating-flow.ts]: I guess this is preference, and maybe following the convention we have right now, but maybe put that above (outside the function)

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts [hunk 3]
```diff
@@ -100,18 +114,26 @@ export function sortByTopRated() {
...
-export function checkFirstItem(title: string): void {
+export function checkFirstItem(productName: string): void {
   cy.get('cx-product-list-item .cx-product-name')
     .first()
-    .should('contain', title);
+    .should('contain', productName);
 }
-export function createDefaultQueryRoute(alias: string): void {
+
+export function createGenericQuery(alias: string): void {
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts]: maybe call it createGenericProductQuery, because other e2e tests uses stubbing as well, and having it called generic is maybe false. This is only true for product-search

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts [hunk 4]
```diff
@@ -30,30 +26,36 @@ export function productPricingFlow() {
...
-
-  cy.wait('@query_price_asc');
-
-  cy.get('.page-item.active > .page-link').should('contain', '2');
-
-  cy.get('cx-product-list-item:first .cx-product-name').should(
-    'contain',
-    'DSC-W180'
-  );
+  cy.get('cx-product-list-item .cx-product-name')
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: Put the cx-product-list-item and/or .cx-product-name into a variable since we are re-using them, or put this line until the should match into a function because we're re-using them too or both!

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts [hunk 5]
```diff
@@ -30,30 +26,36 @@ export function productPricingFlow() {
...
+    .invoke('text')
+    .should('match', /\w+/)
+    .then(firstProduct => {
+      // Navigate to next page
+      cy.get('.page-item:last-of-type .page-link:first').click();
+      cy.get('.page-item.active > .page-link').should('contain', '2');
+
+      cy.wait('@query');
+
+      cy.get('cx-product-list-item .cx-product-name')
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: same as above

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts [hunk 6]
```diff
@@ -30,30 +26,36 @@ export function productPricingFlow() {
...
+      // Sort by price low to high
+      cy.get('cx-sorting .ng-select:first').ngSelect(
+        PRODUCT_LISTING.SORTING_TYPES.BY_PRICE_ASC
+      );
+
+      cy.wait('@query_price_asc');
+
+      cy.get('.page-item.active > .page-link').should('contain', '2');
+
+      cy.get('cx-product-list-item .cx-product-name')
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: ^

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts [hunk 7]
```diff
@@ -30,30 +26,36 @@ export function productPricingFlow() {
...
-
-  cy.get('.page-item.active > .page-link').should('contain', '2');
-
-  cy.get('cx-product-list-item:first .cx-product-name').should(
-    'contain',
-    'DSC-W180'
-  );
+  cy.get('cx-product-list-item .cx-product-name')
+    .first()
+    .invoke('text')
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: I don't know if we want to standardized things, but I see in most test, we usually do a .then($name) and get the name through .text() and do things with it, *but I find this solution better and cleaner*. Just a thought for me to know

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts [hunk 8]
```diff
@@ -30,30 +26,36 @@ export function productPricingFlow() {
...
+    .should('match', /\w+/)
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: should put a comment for the regex saying that it is taking the first word in the string

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts (hunk 1 above)
Comment (hackergil) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: This is working for me. Can you recheck?

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-rating-flow.ts (hunk 2 above)
Comment (hackergil) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-rating-flow.ts]: No, because no other function is using this.

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts (hunk 3 above)
Comment (hackergil) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts]: If it is inside product search, it is a product query by default after the fact of where it's being imported from. I don't think we need to rename this.

Comment (hackergil) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts]: Done.

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts (hunk 8 above)
Comment (hackergil) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: I think that comment would be noise since this regex is very general.

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts [hunk 9]
```diff
@@ -25,35 +26,41 @@ export function productPricingFlow() {
...
+  cy.get(productItemSelector).should(
     'have.length',
     PRODUCT_LISTING.PRODUCTS_PER_PAGE
   );
 
-  checkFirstItem('DSC-S930');
+  cy.get(productNameSelector)
+    .first()
+    .invoke('text')
+    .should('match', /\w+/)
```
Comment (bgambocjaviniar) [inline projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: I was thinking maybe putting the
cy.get(name)
.first
.invoke('text')
.should

inside a function in the helper and call it here since we're checking them 3 times

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts (hunk 1 above)
Comment (bgambocjaviniar) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: I'll recheck once dev-17 is back on, but I believe after that all is fine.

One key thing that I see is that this ticket is missing the other mobile tests that Bill mentioned for the tickets.
- mobile/cart
- mobile/added to cart modal 
were failing in yesterday's regression build

Comment (hackergil) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: yes, they are failing but there is another ticket for those.

File: projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts (hunk 9 above)
Comment (hackergil) [reply projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts]: It is being used 3 times, but one in a different way, which makes it only two. I'll refactor it anyway
