### PR TITLE
fix: payment details step

### LINKED ISSUE #3323: Unable to add a payment method + billing address issue
Screen Shot 2019-06-21 at 3 51 49 PM

Payment details throws an error after you enter your details and press "continue".
This also prevents the user from continuing the order process.

### PR DESCRIPTION
**Pull request by kacperknapik**
Closes #3323

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-method.component.ts [hunk 1]
```diff
@@ -151,60 +148,43 @@ export class PaymentMethodComponent implements OnInit, OnDestroy {
...
-        : this.deliveryAddress;
-
-      this.checkoutPaymentService.createPaymentDetails(payment);
-      this.checkoutService.clearCheckoutStep(3);
-      this.newPayment = newPayment;
-    } else if (this.selectedPayment && this.selectedPayment.id === payment.id) {
-      this.checkoutPaymentService.setPaymentDetails(payment);
-      this.checkoutService.clearCheckoutStep(3);
+    const details: PaymentDetails = { ...paymentDetails };
+    details.billingAddress = billingAddress
```
Comment (Pucek9) [inline projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-method.component.ts]: etails.billingAddress = billingAddress || this.deliveryAddress;
