### PR TITLE
feat: add to cart wrong message fixed

### LINKED ISSUE #3101: Add to cart: message is misleading if you add qty more than 1
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Mac
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Login
Go to a product that's not currently in your cart.
Add Qty 2 of the product

**Actual Result**
You get a message that the product was already in your cart and the qty has been updated. 
Doesn't happen if you add qty1. 
addQty2

### PR DESCRIPTION
**Pull request by mirkosoft**
closes #3101

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.ts [hunk 1]
```diff
@@ -74,8 +75,18 @@ export class AddToCartComponent implements OnInit {
...
     }
-    this.openModal();
-    this.cartService.addEntry(this.productCode, this.quantity);
+    // check item is already present in the cart
+    // so modal will have proper header text displayed
+    this.cartService
+      .getEntry(this.productCode)
+      .subscribe(entry => {
+        if (entry) {
+          this.increment = true;
```
Comment (RadhepS) [inline projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.ts]: Need to set this to false at the end of the subscribe or you'll never get the old "item(s) added to your cart" again.

Comment (mirkosoft) [reply projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.ts]: right, great spot here! already pushed a change
