### PR TITLE
GH-4555: Fix form validation

### LINKED ISSUE #4555: Form validation guest email form
### Steps to reproduce

Add product to cart > start guest checkout
Enter email, when typing the email confirmation you see the validation before submitting

### Intended behavior

Check UX guidelines. Basically, the form error should not be shown before submitting the form.

### PR DESCRIPTION
**Pull request by LTiger14**
Closes #4555

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/user/checkout-login/checkout-login.component.ts [hunk 1]
```diff
@@ -46,7 +46,10 @@ export class CheckoutLoginComponent implements OnDestroy {
```
Comment (bgambocjaviniar) [inline projects/storefrontlib/src/cms-components/user/checkout-login/checkout-login.component.ts]: good good, I can approve tomorrow morning after talking!
Also, I think in the form control for email confirmation, the custom validation is redundant, because email must match anyway. I think its better to remove it.
Lastly, should we align the message to keep conciseness with the update email form or not in terms of validations
