### PR TITLE
fix(@spartacus/storefront): Clear error messages after registering

### LINKED ISSUE #756: Error banner does not go away when registering
From #730 - smoke testing Dec 18 lib release
Tried to register using email address aaa@aaa.aaa, which was not a valid email address. So the banner saying it wasn't valid appears. Then I finish logging in (with a correct email address). But the banner is still there.

### PR DESCRIPTION
**Pull request by marlass**
I used a similar approach to the login action. After successful register, we remove all error messages.

Closes #756

### CODE REVIEW

**Comment by kacperknapik** [comment]
just a though: should we really remove ALL of the error messages?
I think there might be a scenario where we should have an error message (not login/register-related)

File: projects/storefrontlib/src/lib/user/components/register/register.component.ts [hunk 1]
```diff
@@ -64,6 +67,7 @@ export class RegisterComponent implements OnInit, OnDestroy {
       .pipe(
         switchMap(data => {
           if (data && data.access_token) {
+            this.globalMessageService.remove(GlobalMessageType.MSG_TYPE_ERROR);
```
Comment (kacperknapik) [inline projects/storefrontlib/src/lib/user/components/register/register.component.ts]: if we would like to delete login/register-related error messages only, we should pass a second parameter to this function with an index of the message. FYI @marlass

Comment (marlass) [reply projects/storefrontlib/src/lib/user/components/register/register.component.ts]: I think we should remove everything. And we really can't know which one. We would need to check text content of them.
