### PR TITLE
fix: improve page context serialization in state

### LINKED ISSUE #6388: Improve page context serialization in state
If the page context is of type CONTENT_PAGE, then there's no need to included the ID as part of the serialized page context value in the state.

### PR DESCRIPTION
**Pull request by znikola**
closes #6388

### CODE REVIEW

File: projects/core/src/util/serialization-utils.ts [hunk 1]
```diff
@@ -51,10 +52,39 @@ export function makeErrorSerializable(
...
+ *
+ * @param pageContext to serialize
+ */
+export function serializePageContextForState(pageContext: PageContext): string {
+  if (!pageContext) {
+    return CURRENT_CONTEXT_KEY;
+  }
+
+  if (pageContext.type === PageType.CONTENT_PAGE) {
+    return `${pageContext.type}`;
```
Comment (dunqan) [inline projects/core/src/util/serialization-utils.ts]: why not just `return PageType.CONTENT_PAGE`?

File: projects/core/src/util/serialization-utils.ts [hunk 2]
```diff
@@ -51,10 +52,39 @@ export function makeErrorSerializable(
...
+/**
+ * Serializes the provided page context in a suitable way for the Spartacus' state.
+ *
+ * This means that the method will not append the provided page context's ID if it's of type CONTENT_PAGE.
+ * Otherwise, `serializePageContext()` will be used.
+ *
+ * @param pageContext to serialize
+ */
+export function serializePageContextForState(pageContext: PageContext): string {
+  if (!pageContext) {
```
Comment (dunqan) [inline projects/core/src/util/serialization-utils.ts]: this one is already covered in sub-function, do we need to do it twice?

File: projects/core/src/util/serialization-utils.ts [hunk 3]
```diff
@@ -51,10 +52,39 @@ export function makeErrorSerializable(
...
+
+/**
+ * Serializes the provided page context in a suitable way for the Spartacus' state.
+ *
+ * This means that the method will not append the provided page context's ID if it's of type CONTENT_PAGE.
+ * Otherwise, `serializePageContext()` will be used.
+ *
+ * @param pageContext to serialize
+ */
+export function serializePageContextForState(pageContext: PageContext): string {
```
Comment (dunqan) [inline projects/core/src/util/serialization-utils.ts]: It's not for the state in general AFAIK, but for the component-specific state, so the name might be misleading.
I would also consider keeping it in `core/src/cms` folder instead of making it a global util.

File: projects/core/src/util/serialization-utils.ts (hunk 1 above)
Comment (znikola) [reply projects/core/src/util/serialization-utils.ts]: Done

File: projects/core/src/util/serialization-utils.ts (hunk 2 above)
Comment (znikola) [reply projects/core/src/util/serialization-utils.ts]: Not relevant anymore

File: projects/core/src/util/serialization-utils.ts (hunk 3 above)
Comment (znikola) [reply projects/core/src/util/serialization-utils.ts]: Done.
