### PR TITLE
Scroll to Tabs on page and Click Reviews tab on click Show Reviews

### LINKED ISSUE #1437: Clicking on show reviews on pdp page doesn't go to the reviews section
## Environment Details
* Spartacus: dev branch
* Browser: chrome

## Steps to Reproduce
Go to pdp page of a product, for eg: http://localhost:4200/en/USD/product/458542
Click on "Show reviews"
showreviews

## Observed Results
Nothing happens.

## Expected Results
It should navigate to the reviews section of the page

### PR DESCRIPTION
**Pull request by Zeyber**
Fixes #1437

### CODE REVIEW

File: projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts [hunk 1]
```diff
@@ -44,7 +39,52 @@ export class ProductSummaryComponent {
     );
   }
 
-  launchReview() {
-    this.openReview.emit();
+  // Get Tabs Component if exists on page
+  private getTabsComponent(): Element {
+    const elements: HTMLCollectionOf<Element> = document.getElementsByClassName(
```
Comment (Pucek9) [inline projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: I think in this case we can use directive selector
```ts
  private getTabsComponent(): HTMLElement {
    return document.querySelector(
      'cx-product-tabs'
    );
  }
```

File: projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts [hunk 2]
```diff
@@ -44,7 +39,52 @@ export class ProductSummaryComponent {
...
+      'Tabs'
+    );
+
+    return elements.length > 0 ? elements[0] : null;
   }
+
+  // Get Reviews Tab if exists on page
+  private getReviewsTab(): HTMLElement {
```
Comment (Pucek9) [inline projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: It will be nice to have property type Observable<boolean>, allows us to hide "Show reviews" button in case, when Reviews are not displayed in tabs

**Comment by Zeyber** [comment]
Also needs to omit clicking reviews tab if it is already open or use .active classes

File: projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts [hunk 3]
```diff
@@ -44,7 +45,83 @@ export class ProductSummaryComponent {
...
+
+      // Look through h3 tab elements until finding tab with Reviews reference
+      for (const h3Element of Array.from(h3Elements)) {
+        if (h3Element.innerHTML.indexOf(reviewsTabTitle) > -1) {
+          return h3Element;
+        }
+      }
+    }
+
+    return null;
```
Comment (Pucek9) [inline projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: I think it's unnecessary

Comment (Zeyber) [reply projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: Its needed to perform the click action on the tab. It could be possible to invoke the selection without using a "click" though.

File: projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts [hunk 4]
```diff
@@ -44,7 +45,83 @@ export class ProductSummaryComponent {
...
+  }
+
+  // Scroll to views component on page and click "Reviews" tab
+  showReviews() {
```
Comment (Pucek9) [inline projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: I don't think so we need to attend negative situation (we can't click button if it doesn't exist). Console logs are undesirable, but if you like lets import { ServerConfig } from '@spartacus/core';

then code can looks like:
```ts
const reviewsTab = this.getReviewsTab();
const reviewsComponent = this.getReviewsComponent();

if (reviewsTab && reviewsComponent) {
  reviewsComponent.scrollIntoView();
  this.clickTabIfInactive(reviewsTab);
} else {
  this.warn(`Cannot find tabs or Reviews component');
}

////

clickTabIfInactive(tab: HTMLElement): void {
  const reviewsTab = this.getReviewsTab();
  if (
    !tab.classList.contains('active') ||
    tab.classList.contains('toggled')
  ) {
    tab.click();
  }
}

private warn(text: string): void { // In the future it will be moved to logger service/global function
  if (!this.config.production) {
    console.warn(text)
  }
}
```

File: projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts [hunk 5]
```diff
@@ -44,7 +45,83 @@ export class ProductSummaryComponent {
     );
   }
 
-  launchReview() {
-    this.openReview.emit();
+  // Checks if product has reviews
```
Comment (Pucek9) [inline projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: unnecessary comment

File: projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts (hunk 3 above)
Comment (Pucek9) [reply projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: function in default returns undefined, undefined == null ;)

File: projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts (hunk 5 above)
Comment (Zeyber) [reply projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: Whoops forgot to remove that

File: projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts (hunk 4 above)
Comment (Zeyber) [reply projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: Ah you're right. Those checks are redundant now.

File: projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts (hunk 3 above)
Comment (Zeyber) [reply projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.ts]: Oh right yes. Sorry I misunderstood it as the entire method.

**Comment by Zeyber** [comment]
> Please resolve conflicts

Conflicts resolved. Please verify
