### PR TITLE
GH-2472: Fix for svg

### LINKED ISSUE #2472: Support mixture of icon formats
The configurable icons are currently based on a single configuration for the technical icon format. This is insufficient for our icons and more flexibility is required. This ticket brings a flexible solution that allows to mix SVG and font based icons in one storefront as well as different font libraries for the icons.

### PR DESCRIPTION
**Pull request by LTiger14**
Closes #2472

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/misc/icon/icon.component.ts [hunk 1]
```diff
@@ -37,7 +39,7 @@ export class IconComponent {
    * Indicates whether the icon is configured to use SVG or not.
    */
   get useSvg(): boolean {
```
Comment (tobi-or-not-tobi) [inline projects/storefrontlib/src/cms-components/misc/icon/icon.component.ts]: what about we make this:

```
useSvg(type: ICON_TYPE): boolean {
    return this.iconLoader.useSvg(type);
}
```

And pass in the type from the UI? 
same for `getSvgPath`.
