### PR TITLE
fix for failing tests (GH-2376)

### LINKED ISSUE #2376: Fix getting card content for payment info
It causes failing unit test in order details component

### PR DESCRIPTION
**Pull request by mirkosoft**
closes #2376

### CODE REVIEW

File: projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/review-submit/review-submit.component.ts [hunk 1]
```diff
@@ -11,8 +13,6 @@ import {
   UserService,
   TranslationService,
 } from '@spartacus/core';
-import { Observable, combineLatest } from 'rxjs';
```
Comment (Pucek9) [inline projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/review-submit/review-submit.component.ts]: it's not so dumb 😄
