### PR TITLE
fix(@spartacus/storefront): avoid infinite loops, use onPush change detection

### LINKED ISSUE #1099: Bug in category-page.component.ts
```
get template$(): Observable<string> {
    return this.cmsService.getCurrentPage().pipe(map(page => page.template));
 }
```
When `language changed`, `page` can be undefined. So, there needs a check for `page` data. And, I added a console.log inside the map, and found infinite log messages.

### PR DESCRIPTION
**Pull request by tobi-or-not-tobi**
closes #1099

### CODE REVIEW

**Comment by tobi-or-not-tobi** [comment]
The actual infinite loop is caused by the StoreDevtoolsModule. This is causing a change detection every sec. It's still best practice to stick to OnPush.

File: projects/storefrontlib/src/lib/ui/pages/category-page/category-page.component.ts [hunk 1]
```diff
@@ -26,8 +27,12 @@ export class CategoryPageComponent {
     return this.activeRoute.params.pipe(map(params => params['query']));
   }
 
-  get template$(): Observable<string> {
-    return this.cmsService.getCurrentPage().pipe(map(page => page.template));
+  private get template$(): Observable<string> {
+    return this.cmsService.getCurrentPage().pipe(
+      map(page => {
+        return page.template;
```
Comment (WeizhengSap) [inline projects/storefrontlib/src/lib/ui/pages/category-page/category-page.component.ts]: We need `page` check before `return page.template`.
