### PR TITLE
fix: routing to login page if protected

### LINKED ISSUE #4765: Early Login: Homepage is displayed after signing out
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: https://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/login

**Steps to Reproduce**
- enable early login
```typescript
routing: {
   protected: true,
   /* ... */
}
````
- Sign in
- Sign out

**Actual Result**
Upon signing out, the homepage is displayed. 

**Expected Result**
The login page should be displayed instead.

### PR DESCRIPTION
**Pull request by kacperknapik**
Closes #4765

### CODE REVIEW

File: projects/storefrontlib/src/cms-components/user/logout/logout-guard.ts [hunk 1]
```diff
@@ -30,14 +52,20 @@ export class LogoutGuard implements CanActivate {
...
-          }
-        })
+        filter(hasPage => !hasPage),
+        tap(() => this.redirect())
       );
   }
 
+  protected redirect(): void {
+    const cxRoute =
+      this.protectedRoutes && this.protectedRoutes.isAppProtected()
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/user/logout/logout-guard.ts]: Redirecting to a different page than before (to login instead of home - even if homepage is not protected) is a functional breaking change (it may surprise customers). To avoid that, let's also check if the feature level is `1.4`.

File: projects/storefrontlib/src/cms-components/user/logout/logout-guard.ts [hunk 2]
```diff
@@ -30,14 +52,20 @@ export class LogoutGuard implements CanActivate {
         type: PageType.CONTENT_PAGE,
       })
       .pipe(
-        tap(hasPage => {
-          if (!hasPage) {
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/user/logout/logout-guard.ts]: The initial idea of Tobais was to allow customers to implement logout landing page, if they want. By default in our sample data there is no such a 'logout' CMS page, so we fallback to redirecting to other page (home). If you don't mind, you can leave a code comment here with the original purpose - for future reference.

The introduced `filter` doesn't allow for custom `logout` CMS page.

File: projects/core/src/routing/protected-routes/protected-routes.service.ts [hunk 3]
```diff
@@ -22,6 +22,13 @@ export class ProtectedRoutesService {
     }
   }
 
+  /**
+   * Tells if the app is protected
+   */
+  isAppProtected(): boolean {
```
Comment (Platonn) [inline projects/core/src/routing/protected-routes/protected-routes.service.ts]: Is it really needed? What do you thing about simply making `shouldProtect` public?

Comment (kacperknapik) [reply projects/core/src/routing/protected-routes/protected-routes.service.ts]: I'm ok with making `shouldProtect` public I guess. But on the other hand, I would like to hide it behind a method, so we have this one layer, in case we change `shouldProtect` to something else. so only the method would be public, but the implementation would be hidden and protected/private - future proof solution

File: projects/storefrontlib/src/cms-components/user/logout/logout-guard.ts (hunk 2 above)
Comment (kacperknapik) [reply projects/storefrontlib/src/cms-components/user/logout/logout-guard.ts]: Isn't the new solution exactly the same as the previous one, but more elegant? I cannot see a scenario where one would work and another would not. Can u give me such example?

Comment (Platonn) [reply projects/storefrontlib/src/cms-components/user/logout/logout-guard.ts]: `filter(hasPage => !hasPage),` will never emmit a value if the `logout` page exists in CMS.
So the guard will never emmit value.
So you will never navigate to this page.

Comment (kacperknapik) [reply projects/storefrontlib/src/cms-components/user/logout/logout-guard.ts]: fair enough, reverting

File: projects/core/src/routing/protected-routes/protected-routes.service.spec.ts [hunk 4]
```diff
@@ -158,4 +158,36 @@ describe('ProtectedRoutesService', () => {
       });
     });
   });
+
+  describe('shouldProtect', () => {
+    describe('when app not protected', () => {
+      beforeEach(() => {
+        beforeEachWithConfig({
+          protected: false,
+          routes: {
```
Comment (Platonn) [inline projects/core/src/routing/protected-routes/protected-routes.service.spec.ts]: is this config chunk needed?

(applies also to line 182)

File: projects/storefrontlib/src/cms-components/user/logout/logout-guard.spec.ts [hunk 5]
```diff
@@ -88,5 +120,47 @@ describe('LogoutGuard', () => {
...
+    });
+
+    // TODO(issue:5666) Deprecated since 1.4
+    it('should redirect to login page if app protected', () => {
+      spyOn(featureConfigService, 'isLevel').and.returnValue(true);
+
+      spyOnProperty(
+        protectedRoutesService,
+        'shouldProtect',
+        'get'
```
Comment (Platonn) [inline projects/storefrontlib/src/cms-components/user/logout/logout-guard.spec.ts]: Why do we need `'get'` here?
